### ISSUE TITLE
[BUG] Window previews may be 1/4 the selected preview size in multiple display setups 

### ISSUE THREAD

**Issue by surfous** [ejbills/DockDoor#392]
## Describe the bug
Previews for windows on an extended display are 1/4 the selected preview size when the active window is on the primary display

## Steps to reproduce
- Have windows open on both displays; active window on the primary display
  - Previews of windows on the primary display are the full size of the preview
  - Previews of windows on the extended display are 1/4 size of the preview
- Click a window on the extended display to make it active
  - Wait for window image cache lifespan to elapse so all window previews update
  - Previews of all windows are the full size of the preview
- Click a window on the primary display to make it active
  - Wait for window image cache lifespan to elapse so all window previews update
  - Previews of windows on the primary display are the full size of the preview
  - Previews of windows on the extended display are again 1/4 size of the preview

## Expected behavior
Window previews should consume the entire preview size regardless which display the window is currently on and regardless which display the currently _active_ window is on.

## Actual behavior
New preview images of windows on the extended display when the active window is on the primary display are 1/4 the size the of preview area in the pop-up. 

### Active window on primary display
Safari window is on primary display
Mail, Fantastical, Messages each have one window on the extended display
Notes has one window on the primary display and one window on the extended display
Using the dock on the primary display
Windows on the extended display have previews that are 1/4 the preview size (bug behavior)

https://github.com/user-attachments/assets/73e97fb5-5a59-406c-ac79-12bc3a935719

### Active window on extended display
Window locations are the same as above
Using the dock on the primary display
All previews are the full preview size (expected behavior)

https://github.com/user-attachments/assets/f9270ce8-84b2-4bc3-ae48-3f6aaae44d50

## Environment
 - macOS version: 14.6.1 Sonoma
 - App version: 1.3.2
 - Display hardware
   - built-in 16-inch MacBook Pro Display 3456 x 2234
   - extended external display 31.5-inch 3840 x 2160

## Additional context
The cache timeout for any preview must elapse before seeing an update that exhibits the problem. 

- [x] I have reviewed the open issues to ensure this is not a duplicate

**Comment by ejbills** [comment]
Hmm, the backing scale factor is incorrect. I will take a look at this.

**Comment by ejbills** [comment]
Fixed in 1.4

**Comment by surfous** [comment]
Thank you for looking at this @ejbills. I updated to v1.4, and the reported behavior was still occurring both before and after upgrading MacOS from Sonoma to Sequoia. On a whim, I changed the Window Image Resolution Scale from 1 to 2, and that resolved the problem under v1.4. Of course, I don't know if this settings change would have had the same effect prior to DockDoor v1.4, but it's a sufficient workaround for my purposes.
