### ISSUE TITLE
[BUG] border missing in dock preview in the new design

### ISSUE THREAD

**Issue by wfern** [ejbills/DockDoor#677]
## Describe the bug
Missing top or bottom border missing around the elements in dock preview on MacOS Sequoia 15.5 after update to version 1.20 (new design).

<img width="199" height="65" alt="Image" src="https://github.com/user-attachments/assets/c48646f6-bf81-4633-ba46-ac0aa0b7232a" />

I tried the beta channel but happen the same thing except it was the bottom border missing.

## Environment
 - macOS version: macOS 15.5 Sequoia
 - App version: 1.20

- [x] I have reviewed the open issues to ensure this is not a duplicate

**Comment by ejbills** [comment]
Is this with an external monitor? They look fine on my macbook display

**Comment by wfern** [comment]
Yes, I'm using a external monitor with Mac Mini M1

**Comment by wfern** [comment]
The only place i saw that kind of "bug" or "border" is on the control center:

<img width="449" height="386" alt="Image" src="https://github.com/user-attachments/assets/c337514c-20d6-4bcd-9e17-21d1ec204c33" />

What is the name of this "element" on swift? Do you know any fix for that?

**Comment by ejbills** [comment]
I think it's just a macOS 26 beta bug, these are just .stroke() modifiers in swiftUI

Wait.. are you even on macOS 26?

**Comment by wfern** [comment]
No, I'm on Sequoia 15.5

**Comment by ejbills** [comment]
Can you try 1.21? I switched to using .strokeBorder which should fix it based on this: https://stackoverflow.com/questions/67126516/swiftui-roundedrectangle-cutting-off-on-the-bottom

**Comment by wfern** [comment]
I tried but it's still the same.

I tried to change a lot of settings on macos like "reduce transparency" but it keeps that way.

If I use light mode the borders don't appear in control center, but no success on dockdoor:

<img width="350" height="393" alt="Image" src="https://github.com/user-attachments/assets/ad6ef6bf-bd2b-4861-a23c-534fab258a4b" />

I can try running the project on my computer and try changing the properties to see if it works since there's no way to reproduce it on your computer.

Do you have any tips on what I can try changing?

**Comment by ejbills** [comment]
@wfern can you please try the latest beta version? During my research, it appears this is a long standing SwiftUI bug so I went ahead and made my own border implementation. Let me know your results!

**Comment by wfern** [comment]
It's perfect now, thanks!

<img width="428" height="327" alt="Image" src="https://github.com/user-attachments/assets/d1f57e0d-f505-4dd4-81fa-9a5ab2e83639" />

**Comment by ejbills** [comment]
Thanks for confirming @wfern - released under 1.21.1
